// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEmr5bk4xRP2xCF51aTC8t0DCC3V5V7hE',
    appId: '1:730236073734:web:bb674a3ffaf4ae4a281087',
    messagingSenderId: '730236073734',
    projectId: 'vibeme-f99c0',
    authDomain: 'vibeme-f99c0.firebaseapp.com',
    storageBucket: 'vibeme-f99c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGUzye-g8Se_RZUlIlNGbjjow1fLLfCDE',
    appId: '1:730236073734:android:584382180d2c3ed9281087',
    messagingSenderId: '730236073734',
    projectId: 'vibeme-f99c0',
    storageBucket: 'vibeme-f99c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUO0v38F1g_9AuYs0_FFIUVOoCJQ_Uuts',
    appId: '1:730236073734:ios:7d931cb3b50a74d8281087',
    messagingSenderId: '730236073734',
    projectId: 'vibeme-f99c0',
    storageBucket: 'vibeme-f99c0.firebasestorage.app',
    iosBundleId: 'com.nitish.vibeme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUO0v38F1g_9AuYs0_FFIUVOoCJQ_Uuts',
    appId: '1:730236073734:ios:a8116c8cd55a50b7281087',
    messagingSenderId: '730236073734',
    projectId: 'vibeme-f99c0',
    storageBucket: 'vibeme-f99c0.firebasestorage.app',
    iosBundleId: 'com.example.vibeme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEmr5bk4xRP2xCF51aTC8t0DCC3V5V7hE',
    appId: '1:730236073734:web:e1c04d500a15b752281087',
    messagingSenderId: '730236073734',
    projectId: 'vibeme-f99c0',
    authDomain: 'vibeme-f99c0.firebaseapp.com',
    storageBucket: 'vibeme-f99c0.firebasestorage.app',
  );

}